name: Docker

on:
  push:
    # Publish `main` as Docker `latest` image.
    branches:
      - main

  # Run tests for any PRs.
  pull_request:

jobs:
  # Run tests.
  # See also https://docs.docker.com/docker-hub/builds/automated-testing/
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run
        run: |
          docker-compose up
